//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoteca.DataAccess.TRAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInfoteca_Usuario
    {
        public int TN_ID { get; set; }
        public string TC_Usuario { get; set; }
        public string TC_Idetificacion { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_PriApellido { get; set; }
        public string TC_SegApellido { get; set; }
        public string TC_Tipo_Autentificacion { get; set; }
        public string TC_Tipo_Usuario { get; set; }
        public string TC_Email { get; set; }
        public Nullable<int> TN_Intentos { get; set; }
        public string TC_Usuario_Actualiza { get; set; }
        public Nullable<System.DateTime> TF_FecActualiza { get; set; }
        public string TC_Observaciones { get; set; }
        public bool TC_Eliminado { get; set; }
        public string TC_Tipo_Identificacion_ID { get; set; }
        public string TC_Institucion_ID { get; set; }
        public string TC_Oficina_ID { get; set; }
        public bool TB_Activo { get; set; }
    }
}
