//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoteca.DataAccess.TRAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInfoteca_Mensaje
    {
        public int TN_ID { get; set; }
        public string TC_Formato { get; set; }
        public string TC_Accion { get; set; }
        public string TC_Tabla { get; set; }
        public string TC_Mensaje { get; set; }
        public bool TB_Activo { get; set; }
    }
}
