//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoteca.DataAccess.TRAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInfoteca_Propiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TInfoteca_Propiedad()
        {
            this.TInfoteca_Noticia_Propiedad = new HashSet<TInfoteca_Noticia_Propiedad>();
        }
    
        public int TN_Id { get; set; }
        public string TC_TipoPropiedad { get; set; }
        public string TC_Ubicacion { get; set; }
        public bool TB_Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TInfoteca_Noticia_Propiedad> TInfoteca_Noticia_Propiedad { get; set; }
    }
}
