//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoteca.DataAccess.TRAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInfoteca_Noticia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TInfoteca_Noticia()
        {
            this.TInfoteca_Noticia_Imagen = new HashSet<TInfoteca_Noticia_Imagen>();
            this.TInfoteca_Noticia_Juridica = new HashSet<TInfoteca_Noticia_Juridica>();
            this.TInfoteca_Noticia_Persona = new HashSet<TInfoteca_Noticia_Persona>();
            this.TInfoteca_Noticia_Propiedad = new HashSet<TInfoteca_Noticia_Propiedad>();
            this.TInfoteca_Noticia_Vehiculo = new HashSet<TInfoteca_Noticia_Vehiculo>();
        }
    
        public int TN_Id { get; set; }
        public System.DateTime TF_Fecha_Evento { get; set; }
        public string TC_Descripcion { get; set; }
        public string TC_Sub_Delito { get; set; }
        public string TC_Palabras_Clave { get; set; }
        public Nullable<System.DateTime> TF_Fecha_Creacion { get; set; }
        public int TN_Id_Tipo_Delito { get; set; }
        public int TN_Id_Fuente { get; set; }
        public bool TB_Activo { get; set; }
    
        public virtual TInfoteca_Fuente TInfoteca_Fuente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TInfoteca_Noticia_Imagen> TInfoteca_Noticia_Imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TInfoteca_Noticia_Juridica> TInfoteca_Noticia_Juridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TInfoteca_Noticia_Persona> TInfoteca_Noticia_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TInfoteca_Noticia_Propiedad> TInfoteca_Noticia_Propiedad { get; set; }
        public virtual TInfoteca_Tipo_Delito TInfoteca_Tipo_Delito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TInfoteca_Noticia_Vehiculo> TInfoteca_Noticia_Vehiculo { get; set; }
    }
}
