//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoteca.DataAccess.TRAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInfoteca_Bitacora
    {
        public int TN_Id { get; set; }
        public string TC_Operacion { get; set; }
        public string TC_Usuario { get; set; }
        public string TC_Host { get; set; }
        public System.DateTime TD_Modificado { get; set; }
        public string TC_Tabla { get; set; }
        public int TN_IdObjeto { get; set; }
        public bool TB_Activo { get; set; }
    }
}
